[package]
name = "qfind"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Qfind command-line search"

[dependencies]
anyhow.workspace = true
clap.workspace = true
qfind-core.workspace = true
qfind-tui = { path = "../tui" }
