[package]
name = "qfind-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Qfind terminal UI"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
qfind-core.workspace = true
ratatui.workspace = true
